<?php

DEFINE("MYSQL_HOST","localhost");
DEFINE("MYSQL_USER", "root");
DEFINE("MYSQL_PASSWORD", "");
DEFINE("MYSQL_DATABASE", "phpdemo");

DEFINE("MYSQL_TABLE_USERS", "users");
DEFINE("MYSQL_TABLE_SESSIONS", "sessions");


?>